name: pr
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set up node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: install dependencies
        run: npm i
      - name: run tests
        run: npm test
      - name: setup testspace publisher
        uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{github.repository_owner}}
      - name: publish test results
        run: testspace .testresults/xunit.xml
        if: always()
